### ISSUE TITLE
Chrome Extension Error

### ISSUE THREAD

**Issue by AlanBleiweiss** [GoogleChrome/web-vitals-extension#56] opened 2020-05-08 16:46 UTC
Installed the Chrome extension (Web Vitals .1.1) on my Macbook Pro. (El Capitan v. 10.11.6).  On first install, extension was shown with three errors, however it turned out i didn't have the latest version of Chrome. So I updated that and it's now the latest version - 81.0.4044.138 (Official Build) (64-bit) and there's one error in the extension. 

Unchecked runtime.lastError: Cannot access contents of url "chrome-search://local-ntp/local-ntp.html". Extension manifest must request permission to access this host.
Context
_generated_background_page.html
Stack Trace
_generated_background_page.html:0 (anonymous function)
Nothing to see here, move along.
Unchecked runtime.lastError: Cannot access a chrome:// URL

**Comment by rviscomi** [comment] 2020-05-08 16:54
Looks like a duplicate of #54

**Comment by addyosmani** [comment] 2020-05-08 17:10
Yeah, I'm reading this as a dupe of 54. Closing in favor of fixing that one. Thanks for the report!

**Comment by AlanBleiweiss** [comment] 2020-05-08 17:10
It may be the same error.  Theirs refers to a different URL where the contents couldn't be accessed.  

Sorry if it's the same and this is a duplicate submission.  I'm new here and after reporting last night, was asked to post by Addy Osmani. I only saw that request a few minutes ago.

**Closed by addyosmani** 2020-05-08 17:10 UTC
