### ISSUE TITLE
Extension shows 'metrics unavailable' instead of metrics

### ISSUE THREAD

**Issue by awareness481** [GoogleChrome/web-vitals-extension#78] opened 2020-11-11 22:06 UTC
**Describe the bug**

Clicking on extension popup often shows 'Metrics unavailable while HUD appears to show correct values, See screenshow below

**To Reproduce**

I haven't been able to fully identify the steps to reproduce. I suspect however that it happens when either all values or the CLS value approach zero or are zero.

**Expected behavior**
To show the metrics. As I understand, even if the values are low it should still show them?

**Version:**

- OS w/ version: 
(Xubuntu flavor)
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
- Browser w/ version Chrome 86.0.4240.183 (Official Build)

**Additional context, screenshots, screencasts**

![image](https://user-images.githubusercontent.com/12380586/98869689-d8fcfa80-247a-11eb-88af-4d19f5f41d44.png)

**Comment by nunoperalta** [comment] 2020-11-14 14:49
This is happening often to me too, especially when I do "ajax navigations" from one page to another (but that doesn't do a full page load)

**Comment by EdBoyd** [comment] 2020-12-10 15:27
Yet to see anything other than "Metrics data unavailable." no matter which site i look at, including this page.
Windows 10 
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36

**Comment by awareness481** [comment] 2020-12-23 11:18
FWIW I'm not seeing this error anymore on version `0.4.2`

Chrome: 87.0.4280.88

Could you check if the error still occurs after upgrading to `0.4.2`

**Comment by nunoperalta** [comment] 2020-12-23 12:22
Might be fixed, yes. Thanks! 👍

**Comment by awareness481** [comment] 2020-12-31 08:01
I'm closing this issue as the error doesn't seem to appear anymore.

If your come accross this issue, please make sure you're on version `>=0.4.2` and report back if it still occurs.

**Comment by dubbha** [comment] 2021-02-01 00:27
It does occur to me on version 0.4.2
Chrome Version 88.0.4324.104 (Official Build) (64-bit)

I think I understand the use case now. When I load the page, I get LCP and CLS alright, and FID is waiting for input. I have a search input which updates the URL with the search query right away. After I start typing into the input, and it adds something like "?query=Q" to the current URL, the extension goes "Metrics data unavailable".

I tried other inputs that don't touch the URL, and they seem fine. Not sure if the use case above is considered illegal or something, but I didn't make it up.

**Comment by fgeierst** [comment] 2021-04-02 18:50
I see the same error "Metrics data unavailable." on Edge 89, Win 10, Web Vitals extension 0.4.5

**Comment by Ryan-Ray-Neff** [comment] 2021-04-02 19:02
I'm still seeing the issue as well in Extension 0.4.5, OSX Big Sur 11.2.3, Chrome 89.0.4389.90. 
It looks like there is a workaround though. You can right click on the icon, then, select 'options', then select 'Display HUD overlay` to see an overlay on every page load. Alternately, you can select 'Console logging' to see the output in Dev tools console.

**Comment by RunningCoderLee** [comment] 2021-06-24 15:50
![image](https://user-images.githubusercontent.com/13218863/123293211-6262c800-d546-11eb-87a6-72f5de2b6daf.png)

Anyone has this problem?

extension version: 1.0.0
OS: macOS big sur 11.2.3
Browser version: Microsoft Edge Version 91.0.864.54 (Official build) (arm64)

**Comment by aldarund** [comment] 2021-06-28 23:13
Same, Web Vitals are unavailable for this page

vitals.js:286 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: chrome-extension://ahfhijdlegdabablpippeagghigmibma/node_modules/web-vitals/dist/web-vitals.js

**Comment by MaluNoPeleke** [comment] 2022-04-05 14:09
This still happens with v1.0.2 and Chrome 100

**Comment by rviscomi** [comment] 2022-04-05 15:43
@MaluNoPeleke are you seeing that on all pages? If only on specific pages, could you share their URLs?

**Comment by MaluNoPeleke** [comment] 2022-04-05 16:56
Happens on every page

**Comment by rviscomi** [comment] 2022-04-05 20:37
@MaluNoPeleke thanks for confirming. Does the popup look like the screenshot below?

> <img width="549" alt="image" src="https://user-images.githubusercontent.com/1120896/161844391-6cbf8c69-088d-4ced-bbce-e16c4f6baa59.png">
_(blank area with the message "Web Vitals are unavailable for this page")_

One more thing. If you right click on the popup and select **Inspect**, do you see any error messages in the DevTools console?

> <img width="1079" alt="image" src="https://user-images.githubusercontent.com/1120896/161844678-5e2ed228-8a66-4d3e-9a14-09f6b377b11d.png">
_("Storage empty for key 933747933: [object Object]")_

**Comment by MaluNoPeleke** [comment] 2022-04-06 07:57
Yes, the window looks exactly like this and shows the same error message:
![image](https://user-images.githubusercontent.com/1446541/161925062-eee16e97-4c66-4e8d-afb3-68c123e5cdc2.png)

**Comment by rviscomi** [comment] 2022-04-08 16:55
Thanks for confirming. I can reproduce the error, but only on Google websites, by design.

Can you visit http://example.com/ just to verify that you get the error consistently on every page?

> <img width="551" alt="image" src="https://user-images.githubusercontent.com/1120896/162487245-d8dfba28-6449-4daf-b547-923b3df3a1dd.png">

If that still doesn't work, the only other thing I can think of would be to uninstall and reinstall the extension.

**Comment by MaluNoPeleke** [comment] 2022-04-11 09:50
Removing and installing it again solved the issue

**Comment by rviscomi** [comment] 2022-05-11 20:05
Thanks for confirming. Closing this issue and recommending that anyone experiencing unavailable data reinstall the extension.

**Closed by rviscomi** 2022-05-11 20:05 UTC

**Comment by duncanma-stripe** [comment] 2022-10-10 17:49
> Thanks for confirming. I can reproduce the error, but only on Google websites, by design.

@rviscomi  What do you mean "by design", is there something certain sites are doing (or could do) that blocks this extension? Thanks for the info, not asking for a change, just trying to understand why I get that message on a specific site/page
