### ISSUE TITLE
1.0 version never seems to show me FID.  Always says "waiting for input".

### ISSUE THREAD

**Issue by mmocny** [GoogleChrome/web-vitals-extension#95] opened 2021-07-06 16:01 UTC
**Describe the bug**
All page loads give me LCP and CLS, but FID is stuck at "waiting for input" even when I can use PerformanceObserver to see that there was a FID entry available.

**To Reproduce**
Load a page.  Interact with the page (click on some element which will not navigate away).  Check CWV extension, see there is no FID.

**Expected behavior**

**Version:**

- OS w/ version: MacOS 11.3.1
- Browser w/ version: Google Chrome	91.0.4472.114 (Official Build) (x86_64)

**Additional context, screenshots, screencasts**
<img width="659" alt="Screen Shot 2021-07-06 at 11 57 28 AM" src="https://user-images.githubusercontent.com/474282/124631919-d9a33080-de51-11eb-9532-46e01d3aa9e9.png">
<img width="576" alt="Screen Shot 2021-07-06 at 11 57 24 AM" src="https://user-images.githubusercontent.com/474282/124631943-df007b00-de51-11eb-90ed-bcc4f2370343.png">

**Comment by rviscomi** [comment] 2021-07-07 18:03
Duplicate of https://github.com/GoogleChrome/web-vitals-extension/issues/93, fixed in https://github.com/GoogleChrome/web-vitals-extension/pull/94.

@addyosmani could you release an update to the Chrome Web Store with this fix?

**Comment by smerriman** [comment] 2021-07-13 03:26
Any updates on this? Has been 12 days since the bug was fixed, and with the Google Core Web Vitals update in place, it would be nice to be able to debug properly.

**Comment by rviscomi** [comment] 2022-05-11 20:16
This issue should be fixed for everyone on the latest version. Closing.

**Closed by rviscomi** 2022-05-11 20:16 UTC
